// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtXV5MSg4YSI2XNWYVSmTgvDXn4L4H8f0',
    appId: '1:721836562417:web:8c1ce6a265c174dc895650',
    messagingSenderId: '721836562417',
    projectId: 'fb-revision',
    authDomain: 'fb-revision.firebaseapp.com',
    storageBucket: 'fb-revision.appspot.com',
    measurementId: 'G-MR7DDP1S2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VGvpONkTRdBJflimkiJmk1gO7NtNyV0',
    appId: '1:721836562417:android:695bb71100277e02895650',
    messagingSenderId: '721836562417',
    projectId: 'fb-revision',
    storageBucket: 'fb-revision.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ4NxSJa-UMl6A8Z6FwyOXzjIsV1bW0jg',
    appId: '1:721836562417:ios:4a6de14f8f700ee9895650',
    messagingSenderId: '721836562417',
    projectId: 'fb-revision',
    storageBucket: 'fb-revision.appspot.com',
    iosBundleId: 'com.example.fbRevision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ4NxSJa-UMl6A8Z6FwyOXzjIsV1bW0jg',
    appId: '1:721836562417:ios:134843d4a8bb3cb7895650',
    messagingSenderId: '721836562417',
    projectId: 'fb-revision',
    storageBucket: 'fb-revision.appspot.com',
    iosBundleId: 'com.example.fbRevision.RunnerTests',
  );
}
